# Generated by Django 5.1.7 on 2025-03-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='barcode',
            field=models.CharField(blank=True, help_text='Product barcode (optional)', max_length=100, null=True, unique=True),
        ),
    ]
