# Generated by Django 5.1.7 on 2025-03-27 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_app', '0002_drug_barcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(upload_to='invoice_uploads/')),
                ('file_type', models.CharField(choices=[('PDF', 'PDF Document'), ('IMAGE', 'Image'), ('EXCEL', 'Excel Spreadsheet')], max_length=10)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending Processing'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIALLY_PROCESSED', 'Partially Processed')], default='PENDING', max_length=20)),
                ('processing_notes', models.TextField(blank=True, null=True)),
                ('total_items_found', models.IntegerField(default=0)),
                ('total_items_matched', models.IntegerField(default=0)),
                ('output_file', models.FileField(blank=True, null=True, upload_to='invoice_outputs/')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy_app.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_name', models.CharField(max_length=200)),
                ('extracted_brand', models.CharField(blank=True, max_length=200, null=True)),
                ('extracted_quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('extracted_cost_price', models.CharField(blank=True, max_length=50, null=True)),
                ('extracted_batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('extracted_expiry_date', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('match_status', models.CharField(choices=[('MATCHED', 'Matched to Drug'), ('PARTIAL_MATCH', 'Partially Matched'), ('UNMATCHED', 'No Match Found'), ('MANUALLY_MATCHED', 'Manually Matched'), ('IGNORED', 'Ignored')], default='UNMATCHED', max_length=20)),
                ('match_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('processing_notes', models.TextField(blank=True, null=True)),
                ('is_imported', models.BooleanField(default=False)),
                ('matched_drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy_app.drug')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy_app.invoiceupload')),
            ],
        ),
    ]
