# Generated by Django 5.1.7 on 2025-03-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_app', '0004_alter_invoiceitem_extracted_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_walk_in',
            field=models.BooleanField(default=False, help_text='Indicates if this is a walk-in customer'),
        ),
    ]
